In [30]:
from pathlib import Path
import numpy as np
import pandas as pd
from sds.data.ds_index_gt import load_index_gt
from sds.utils.utils import load_objs

In [10]:
sds_root_path = Path('/data/data/sds')
target_ds_name, dist_ds_name = 'itodd', 'tless'
index_fpath = Path(sds_root_path / target_ds_name / 'index.csv')

In [11]:
objs = load_objs(sds_root_path, target_ds_name, dist_ds_name)
df = load_index_gt(sds_root_path / target_ds_name, objs)
df

Unnamed: 0  scene_num  file_num  itodd_obj_000001  itodd_obj_000002  \
0                0          0         0                 3                 0   
1                1          0         1                 3                 0   
2                2          0         2                 3                 0   
3                3          0         3                 3                 0   
4                4          0         4                 3                 0   
...            ...        ...       ...               ...               ...   
138677      138677        138       675                 0                 0   
138678      138678        138       676                 0                 0   
138679      138679        138       677                 0                 0   
138680      138680        138       678                 0                 0   
138681      138681        138       679                 0                 0   

        itodd_obj_000003  itodd_obj_000004  itodd_obj_000005  \
0                      0                 0                 2   
1                      0                 0                 2   
2                      0                 0                 2   
3                      0                 0                 2   
4                      0                 0                 2   
...                  ...               ...               ...   
138677                 1                 2                 1   
138678                 1                 2                 1   
138679                 1                 2                 1   
138680                 1                 2                 1   
138681                 1                 2                 1   

        itodd_obj_000006  itodd_obj_000007  ...  tless_obj_000021  \
0                      0                 1  ...                 0   
1                      0                 1  ...                 0   
2                      0                 1  ...                 0   
3                      0                 1  ...                 0   
4                      0                 1  ...                 0   
...                  ...               ...  ...               ...   
138677                 2                 1  ...                 0   
138678                 2                 1  ...                 0   
138679                 2                 1  ...                 0   
138680                 2                 1  ...                 0   
138681                 2                 1  ...                 0   

        tless_obj_000022  tless_obj_000023  tless_obj_000024  \
0                      0                 0                 1   
1                      0                 0                 1   
2                      0                 0                 1   
3                      0                 0                 1   
4                      0                 0                 1   
...                  ...               ...               ...   
138677                 1                 1                 0   
138678                 1                 1                 0   
138679                 1                 1                 0   
138680                 1                 1                 0   
138681                 1                 1                 0   

        tless_obj_000025  tless_obj_000026  tless_obj_000027  \
0                      0                 0                 1   
1                      0                 0                 1   
2                      0                 0                 1   
3                      0                 0                 1   
4                      0                 0                 1   
...                  ...               ...               ...   
138677                 0                 0                 3   
138678                 0                 0                 3   
138679                 0                 0                 3   
138680                 0                 0          

In [13]:
obj_num = 1
mask = df[f'itodd_obj_{obj_num:06d}'] > 0
mask

0          True
1          True
2          True
3          True
4          True
          ...  
138677    False
138678    False
138679    False
138680    False
138681    False
Name: itodd_obj_000001, Length: 138682, dtype: bool

In [15]:
df_part = df[mask]
df_part

Unnamed: 0  scene_num  file_num  itodd_obj_000001  itodd_obj_000002  \
0                0          0         0                 3                 0   
1                1          0         1                 3                 0   
2                2          0         2                 3                 0   
3                3          0         3                 3                 0   
4                4          0         4                 3                 0   
...            ...        ...       ...               ...               ...   
138657      138657        138       655                 1                 1   
138658      138658        138       656                 1                 1   
138659      138659        138       657                 1                 1   
138660      138660        138       658                 1                 1   
138661      138661        138       659                 1                 1   

        itodd_obj_000003  itodd_obj_000004  itodd_obj_000005  \
0                      0                 0                 2   
1                      0                 0                 2   
2                      0                 0                 2   
3                      0                 0                 2   
4                      0                 0                 2   
...                  ...               ...               ...   
138657                 1                 0                 0   
138658                 1                 0                 0   
138659                 1                 0                 0   
138660                 1                 0                 0   
138661                 1                 0                 0   

        itodd_obj_000006  itodd_obj_000007  ...  tless_obj_000021  \
0                      0                 1  ...                 0   
1                      0                 1  ...                 0   
2                      0                 1  ...                 0   
3                      0                 1  ...                 0   
4                      0                 1  ...                 0   
...                  ...               ...  ...               ...   
138657                 2                 2  ...                 0   
138658                 2                 2  ...                 0   
138659                 2                 2  ...                 0   
138660                 2                 2  ...                 0   
138661                 2                 2  ...                 0   

        tless_obj_000022  tless_obj_000023  tless_obj_000024  \
0                      0                 0                 1   
1                      0                 0                 1   
2                      0                 0                 1   
3                      0                 0                 1   
4                      0                 0                 1   
...                  ...               ...               ...   
138657                 0                 0                 0   
138658                 0                 0                 0   
138659                 0                 0                 0   
138660                 0                 0                 0   
138661                 0                 0                 0   

        tless_obj_000025  tless_obj_000026  tless_obj_000027  \
0                      0                 0                 1   
1                      0                 0                 1   
2                      0                 0                 1   
3                      0                 0                 1   
4                      0                 0                 1   
...                  ...               ...               ...   
138657                 2                 0                 1   
138658                 2                 0                 1   
138659                 2                 0                 1   
138660                 2                 0          

In [16]:
df.columns

Index(['Unnamed: 0', 'scene_num', 'file_num', 'itodd_obj_000001',
       'itodd_obj_000002', 'itodd_obj_000003', 'itodd_obj_000004',
       'itodd_obj_000005', 'itodd_obj_000006', 'itodd_obj_000007',
       'itodd_obj_000008', 'itodd_obj_000009', 'itodd_obj_000010',
       'itodd_obj_000011', 'itodd_obj_000012', 'itodd_obj_000013',
       'itodd_obj_000014', 'itodd_obj_000015', 'itodd_obj_000016',
       'itodd_obj_000017', 'itodd_obj_000018', 'itodd_obj_000019',
       'itodd_obj_000020', 'itodd_obj_000021', 'itodd_obj_000022',
       'itodd_obj_000023', 'itodd_obj_000024', 'itodd_obj_000025',
       'itodd_obj_000026', 'itodd_obj_000027', 'itodd_obj_000028',
       'tless_obj_000001', 'tless_obj_000002', 'tless_obj_000003',
       'tless_obj_000004', 'tless_obj_000005', 'tless_obj_000006',
       'tless_obj_000007', 'tless_obj_000008', 'tless_obj_000009',
       'tless_obj_000010', 'tless_obj_000011', 'tless_obj_000012',
       'tless_obj_000013', 'tless_obj_000014', 'tless_obj_00001

In [20]:
for col in df.columns:
    if col.startswith('tless') or col.startswith('itodd'):
        df_part = df[df[col] > 0]
        print(f'{col}: {len(df_part)} {df_part[col].mean():.3f}')

itodd_obj_000001: 93820 1.573
itodd_obj_000002: 94340 1.592
itodd_obj_000003: 93082 1.594
itodd_obj_000004: 94460 1.608
itodd_obj_000005: 93802 1.589
itodd_obj_000006: 94002 1.583
itodd_obj_000007: 94940 1.590
itodd_obj_000008: 94442 1.600
itodd_obj_000009: 92962 1.579
itodd_obj_000010: 92062 1.581
itodd_obj_000011: 92582 1.596
itodd_obj_000012: 93402 1.598
itodd_obj_000013: 94382 1.595
itodd_obj_000014: 93700 1.598
itodd_obj_000015: 93982 1.577
itodd_obj_000016: 93082 1.577
itodd_obj_000017: 93800 1.576
itodd_obj_000018: 93882 1.562
itodd_obj_000019: 93142 1.596
itodd_obj_000020: 93822 1.576
itodd_obj_000021: 93622 1.607
itodd_obj_000022: 93762 1.592
itodd_obj_000023: 92402 1.576
itodd_obj_000024: 94020 1.599
itodd_obj_000025: 93802 1.569
itodd_obj_000026: 93242 1.588
itodd_obj_000027: 93720 1.578
itodd_obj_000028: 93260 1.590
tless_obj_000001: 39102 1.159
tless_obj_000002: 40060 1.153
tless_obj_000003: 39020 1.159
tless_obj_000004: 39280 1.165
tless_obj_000005: 40082 1.158
tless_obj_

In [22]:
df_part = df[df['itodd_obj_000001'] > 0].loc[:, ('scene_num', 'file_num')]

In [23]:
df_part

scene_num  file_num
0               0         0
1               0         1
2               0         2
3               0         3
4               0         4
...           ...       ...
138657        138       655
138658        138       656
138659        138       657
138660        138       658
138661        138       659

[93820 rows x 2 columns]

In [24]:
mask = df['itodd_obj_000001'] > 0
df_part = df.loc[mask, ('scene_num', 'file_num')]

In [25]:
df_part

scene_num  file_num
0               0         0
1               0         1
2               0         2
3               0         3
4               0         4
...           ...       ...
138657        138       655
138658        138       656
138659        138       657
138660        138       658
138661        138       659

[93820 rows x 2 columns]

In [27]:
row = df_part.iloc[93819]
row

scene_num    138
file_num     659
Name: 138661, dtype: int64

In [28]:
row.scene_num, row.file_num

(138, 659)

In [52]:
a = np.random.random((4, 5))
a

array([[0.23254075, 0.69858792, 0.41329461, 0.14167963, 0.98224261],
       [0.81854275, 0.12231102, 0.62400232, 0.79981496, 0.23435402],
       [0.36549733, 0.26478514, 0.48785221, 0.00140314, 0.39613823],
       [0.84052649, 0.12860673, 0.20790006, 0.6942449 , 0.14236704]])

In [54]:
b = a >= 0.5
b

array([[False,  True, False, False,  True],
       [ True, False,  True,  True, False],
       [False, False, False, False, False],
       [ True, False, False,  True, False]])

In [55]:
b[-1, :] = False
b

array([[False,  True, False, False,  True],
       [ True, False,  True,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [58]:
m = np.max(b, axis = 1)
m

array([ True,  True, False, False])

In [60]:
x = np.where(m)[0]
x.min(), x.max()

(0, 1)

In [68]:
(a * 15).astype(np.int32)

array([[ 3, 10,  6,  2, 14],
       [12,  1,  9, 11,  3],
       [ 5,  3,  7,  0,  5],
       [12,  1,  3, 10,  2]], dtype=int32)

In [64]:
np.where(b, axis=1)

TypeError: where() got an unexpected keyword argument 'axis'

In [71]:
a = np.random.random((3, 2))
b = np.array([1, -1])
a, b, a @ b

(array([[0.70878354, 0.5384594 ],
        [0.50985333, 0.59698763],
        [0.47829152, 0.43090719]]),
 array([ 1, -1]),
 array([ 0.17032414, -0.0871343 ,  0.04738433]))

In [72]:
c = a @ b
c, c[:2]

(array([ 0.17032414, -0.0871343 ,  0.04738433]),
 array([ 0.17032414, -0.0871343 ]))

In [73]:
c.abs()

AttributeError: 'numpy.ndarray' object has no attribute 'abs'

In [74]:
np.abs(c)

array([0.17032414, 0.0871343 , 0.04738433])